<?php
	echo $this->form;
	if(isset($this->user)):?>
		<div class=''>
			<div class='row col-xs-10'>
				<h4 class='col-xs-3'>Email:</h4><h4 class='col-xs-6'><?=$this->user['email']?></h4>
			</div>
			<div class='row col-xs-10'>
				<h4 class='col-xs-3'>First Name:</h4><h4 class='col-xs-6 highlight'><?=$this->user['first_name']?></h4>
			</div>
			<div class='row col-xs-10'>
				<h4 class='col-xs-3'>Last Name:</h4><h4 class='col-xs-6'><?=$this->user['last_name']?></h4>
			</div>
			<div class='row col-xs-10'>
				<h4 class='col-xs-3'>Age:</h4><h4 class='col-xs-6'><?=$this->user['age']?> years</h4>
			</div>
			<div class='row col-xs-10'>
				<h4 class='col-xs-3'>Created:</h4><h4 class='col-xs-6'><?=date('d F Y',time($this->user['created']))?></h4>
			</div>
		</div>
<?php endif; ?>